[package]
name = "libvopono"
description = "Library for creating and using Linux network namespaces in Rust code"
license = "MIT/Apache-2.0"
version = "0.1.0"
authors = ["James McMurray <jamesmcm03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.0"
nix = "0.19.0"
thiserror = "1.0.22"
